name: Compilar SuperPlugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x   # versión de .NET compatible con TShock 1.4.4.9

      - name: Compilar el plugin
        run: dotnet build SuperPlugin.csproj -c Release

      - name: Subir DLL como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: SuperPlugin
          path: bin/Release/net6.0/*.dll
